### ISSUE TITLE
missing unit for arrangement.addAutoTimeMarker

### ISSUE THREAD

**Issue by mschenkel1985** [IL-Group/FL-Studio-API-Stubs#19]
Hi,
the missing time unit for the first arg in arrangement.addAutoTimeMarker, time, is absolute ticks as you get with transport.getSongPos(2)

**Comment by MaddyGuthridge** [comment]
Awesome! I'll document this soon! Thanks!

**Comment by MaddyGuthridge** [comment]
Fixed! Let me know if [the changed docs](https://il-group.github.io/FL-Studio-API-Stubs/midi_controller_scripting/arrangement/markers/#arrangement.__markers.addAutoTimeMarker) cover things sufficiently :)

**Comment by mschenkel1985** [comment]
I think so.Great jobMatteo SchenkelOn 16 Jul 2024, at 14:22, Maddy Guthridge ***@***.***> wrote:﻿
Fixed! Let me know if the changed docs cover things sufficiently :)
